name: Lint Feature Branch

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - synchronize
      - reopened

jobs:
  detect-changes:
    name: Detect Code Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            python:
              - '**.py'
              - 'pyproject.toml'
            docker:
              - '**/Dockerfile*'
    outputs:
      python: ${{ steps.changes.outputs.python }}
      docker: ${{ steps.changes.outputs.docker }}

  ruff:
    name: Lint Python
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.python == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml

  hadolint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.docker == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile.*
